# Generated by Django 3.2.9 on 2021-11-26 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teebayApi', '0003_buyhistory_renthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyhistory',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyhistory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='buyhistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyhistory', to='teebayApi.product'),
        ),
        migrations.AlterField(
            model_name='renthistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renthistory', to='teebayApi.product'),
        ),
        migrations.AlterField(
            model_name='renthistory',
            name='renter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renthistory', to=settings.AUTH_USER_MODEL),
        ),
    ]
