# Generated by Django 3.2.9 on 2021-11-26 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teebayApi', '0004_auto_20211126_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=60)),
                ('lastname', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='buyhistory',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyhistory', to='teebayApi.user'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uploadedby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teebayApi.user'),
        ),
        migrations.AlterField(
            model_name='renthistory',
            name='renter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renthistory', to='teebayApi.user'),
        ),
    ]
